### PR TITLE
FIX: Member details card

### PR DESCRIPTION
**Pull request by rumaan**
@haxzie Please try recreating and let me know

### CODE REVIEW

**Comment by haxzie-xx** [comment]
So much files changed 🙃

**Comment by rumaan** [comment]
@haxzie Oops. I wasn't on a clean working tree. Pretty sure merge won't screw things up.

**Comment by haxzie-xx** [comment]
Check  the [deploy preview](https://deploy-preview-171--sosc.netlify.com/) something's odd

**Comment by rumaan** [comment]
@haxzie Gotcha! When I forget to `git branch` 🙈 
Check now.

**Comment by haxzie-xx** [comment]
Thanks mate ✨

**Review by haxzie-xx — APPROVED** [review]

**Pull request merged**
