### PR TITLE
Added devhost Event post

### PR DESCRIPTION
**Pull request by suhanacharya**
Tell me if any changes are required

### CODE REVIEW

**Comment by nathanielmathew** [comment]
@coderhawk999 @dhanushp Any idea why the deploy preview isn't working?

**Comment by suhanacharya** [comment]
@nathanielmathew When they tried adding hacknight as subdomains somewhere it must've de-synced

**Comment by dhanushp** [comment]
We recently transferred Netlify from Haxzie to Akashdeep, I guess that might have caused the issue.

**Comment by nathanielmathew** [comment]
@dhanushp Was it transferred to Akashdeep's Netlify account or SOSC's? Because I'm able to see Suhan's deploy preview when I log into the SOSC Netlify account

**Review by nathanielmathew — APPROVED** [review]

**Pull request merged**
