### PR TITLE
Added Girls Who Code 

### PR DESCRIPTION
**Pull request by Basavarajeshwari-Ambi**

### CODE REVIEW

**Comment by nathanielmathew** [comment]
Hey, @Basavarajeshwari-Ambi 
preferably change the slug in index.md, since it currently reads "/clubs/hack-club-sahyadri"

**Comment by Basavarajeshwari-Ambi** [comment]
> Hey, @Basavarajeshwari-Ambi
> preferably change the slug in index.md, since it currently reads "/clubs/hack-club-sahyadri"

updated now.

**Comment by dhanushp** [comment]
Hey @Basavarajeshwari-Ambi , Can you change the logo to square size?

**Comment by Basavarajeshwari-Ambi** [comment]
Logo Updated

**Review by afrzhussain — APPROVED** [review]

**Pull request merged**
