### PR TITLE
Added Event Details For WebVR-AR-Workshop

### PR DESCRIPTION
**Pull request by nathanielmathew**

### CODE REVIEW

**Comment by haxzie-xx** [comment]
@nathanielmathew Looks good :+1:  it'd be cool if you mention the details of the speakers at the end.

**Comment by nathanielmathew** [comment]
@haxzie I would've, but the Speakers are subject to change

**Comment by haxzie-xx** [comment]
What about the feedback link? We have specifically mentioned it because we all tend to forget to do it at the end.

**Comment by haxzie-xx** [comment]
@nathanielmathew I have merged the PR for now, but please keep me in mind to add the feedback links before the workshop.

**Pull request merged**
