### PR TITLE
Issue #37 - Convert the tabs to bottom navigation on mobile devices.

### PR DESCRIPTION
**Pull request by petervasil**

### CODE REVIEW

**Comment by petervasil** [comment]
I think that check which was not successful should be suppressed. What do you think @haxzie ?

**Comment by haxzie-xx** [comment]
@petervasil Thanks for the PR :tada: We'll be working on your changes further to improve the look and feel :)

**Comment by rumaan** [comment]
It isn't seem to be working. Any thoughts @haxzie @petervasil ??

**Comment by haxzie-xx** [comment]
We got few things left in it. As in removing the top nav on mobile devices.

**Comment by petervasil** [comment]
@haxzie @rumaan I wasn`t sure if you want also remove top nav on mobile devices or only add bottom navigation. I can remove top nav on mobile devices if it is required.

**Comment by petervasil** [comment]
@haxzie I fixed it and actual behaviour is that on mobile devices is visible only bottom navbar and on other devices is visible only top navbar. I hope that it is ok, if there are some other things let me now and I can repair it.

**Pull request closed without merging**
