### PR TITLE
hacktoberfest-hacknight-2020

### PR DESCRIPTION
**Pull request by alpha-oss**

### CODE REVIEW

**Review by dhanushp — CHANGES_REQUESTED** [review]
Your code is conflicting with existing code. I would suggest you to delete the changes you have made to Monish.md

**Comment by nathanielmathew** [comment]
It isn't breaking anything but why was Monish.md modified?

**Comment by dhanushp** [comment]
@nathanielmathew His master branch was few commits behind the main branch and he modified Monish.md which created conflict. So had to revert it back so that there isn't any conflict.
Also what do you feel about the event content?

**Review by nathanielmathew — CHANGES_REQUESTED** [review]
Hey @alpha-oss 
Preferably change "Install git bash(windows user only)" to "Install git on your machine (git bash for windows users)"

**Review by nathanielmathew — APPROVED** [review]

**Review by dhanushp — APPROVED** [review]

**Pull request merged**
