### PR TITLE
Added higher quality favicon

### LINKED ISSUE #246: Update favicon to higher quality SOSC logo
the current logo is a really low quality .ico file of the old SOSC logo, 
It would be better if we had a higher quality favicon of our current SOSC logo

### PR DESCRIPTION
**Pull request by nathanielmathew**
Fixes #246 
Replaced the low-quality favicon with a higher quality favicon of the SOSC logo

### CODE REVIEW

**Review by afrzhussain — CHANGES_REQUESTED** [review]
i feel jst the logo would be fine as favicon: not sosc and logo in the favicon

**Comment by nathanielmathew** [comment]
@coderhawk999  Done 👍

**Comment by haxzie** [comment]
Looks good to me :+1:

**Comment by haxzie** [comment]
Looks good to me :+1: but the file size is too large for a favicon. It's around 200+ kb. Can we reduce it to somewhere around <100kb ?

**Review by haxzie — APPROVED** [review]

**Pull request merged**
