### PR TITLE
Sort team according to hierarchy

### LINKED ISSUE #309: Sort Team Designations based on Hierarchy
It would be a lot better to have the team members sorted based on the following hierarchy:
1. President
2. Vice-President
3. General Secretary
4. Heads of Respective Fields
5. Members

### PR DESCRIPTION
**Pull request by nathanielmathew**
Sorted team members based on the following hierarchy:
1. President
2. Vice-President
3. General Secretary
4. Web Admin
5. Heads of Respective Fields
6. Members

### CODE REVIEW

**Comment by dhanushp** [comment]
Looks good to me.

**Review by dhanushp — APPROVED** [review]

**Comment by dhanushp** [comment]
Also, won't it create an issue when we assign co-heads?

**Comment by nathanielmathew** [comment]
Great! I'll merge it by tonight or so if @coderhawk999 does not have any issues with it

**Comment by nathanielmathew** [comment]
> Also, won't it create an issue when we assign co-heads?

Based on our current role-based structure, we aren't using co-heads for each field; It could be added by modifying the code a bit if we do choose to go back to a structure like that

**Comment by afrzhussain** [comment]
Structure Looks good  👍

**Pull request merged**
